version: '3.4'

services:
  locationhunter.webapi:
    image: locationhunter.webapi
    restart: always
    build:
      context: .
      dockerfile: LocationHunter.WebApi/Dockerfile
    depends_on:
      - postgres

  postgres:
    image: postgres:12.1
    restart: always
    environment:
      - POSTGRES_USER=owner
      - POSTGRES_PASSWORD=locationHunter_owner_psswd
      - POSTGRES_DB=locationHunter_db
    ports:
      - "5432:5432"
    volumes:
      - './LocationHunter.Dal/Postgres-data:/var/lib/postgresql/data'