version: '3.7'

services:
  locationhunter.webapi:
    image: locationhunter.webapi
    container_name: webapi
    restart: always
    build:
      context: .
      dockerfile: LocationHunter.WebApi/Dockerfile
