version: '3.4'

services:
  locationhunter.webapi:
    image: locationhunter.webapi
    build:
      context: .
      dockerfile: LocationHunter.WebApi/Dockerfile

  postgres:
    image: postgres:12.1
    environment:
      - POSTGRES_USER=owner
      - POSTGRES_PASSWORD=locationHunter_owner_psswd
      - POSTGRES_DB=locationHunter_db
    ports:
      - "5432:5432"
